export const UnitData = [
  {
    id: 1,
    category: 'Plot',
    unit: 205,
    project_name: 'Park Ave Penthouse',
    area: 'devnagar gota',
    status: 'Rent',
  },
  {
    id: 2,
    category: 'Tower',
    unit: 501,
    project_name: 'Park Ave Penthouse > Tower B > 5th',
    area: 'devnagar gota',
    status: 'Sell',
  },
  {
    id: 3,
    category: 'Bungalow',
    unit: 20,
    project_name: 'Kenneth Summer Home',
    area: 'devnagar gota',
    status: 'Both',
  },
  {
    id: 4,
    category: 'Plot',
    unit: 210,
    project_name: 'Park Ave Penthouse',
    area: 'devnagar gota',
    status: 'Rent',
  },
  {
    id: 5,
    category: 'Tower',
    unit: 205,
    project_name: 'Park Ave Penthouse > Tower B > 9th',
    area: 'devnagar gota',
    status: 'Sell',
  },
  {
    id: 6,
    category: 'Industrial',
    unit: 12,
    project_name: 'Park Ave Penthouse',
    area: 'devnagar gota',
    status: 'Rent',
  },
];
