//For App
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const LOGOUT = 'LOGOUT';
export const SET_TIMER = 'SET_TIMER';

//For Auth
export const LOGIN = 'LOGIN';
export const SIGN_UP_INIT = 'SIGN_UP_INIT';
export const SIGN_UP = 'SIGN_UP';
export const SEND_OTP = 'SEND_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const SELECT_ROLE = 'SELECT_ROLE';

//For Project
export const GET_SELECTED_PROJECT = 'GET_SELECTED_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT_COMMON_DATA = 'GET_PROJECT_COMMON_DATA';

//For Add Project
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_LOCAL_STRUCTURE = 'UPDATE_LOCAL_STRUCTURE';
export const SAVE_STRUCTURE = 'SAVE_STRUCTURE';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const UPDATE_ADMINS = 'UPDATE_ADMINS';
export const RESET_STRUCTURE = 'RESET_STRUCTURE';

//For Sales
export const GET_SALES_DATA = 'GET_SALES_DATA';
export const GET_VISITORS = 'GET_VISITORS';
export const GET_FOLLOWUP_LIST = 'GET_FOLLOWUP_LIST';
export const ADD_VISITOR = 'ADD_VISITOR';
export const ADD_FOLLOW_UP = 'ADD_FOLLOW_UP';
export const GET_PIPELINES = 'GET_PIPELINES';
export const ADD_PIPELINE = 'ADD_PIPELINE';
export const DELETE_PIPELINE = 'DELETE_PIPELINE';
export const MOVE_VISITOR = 'MOVE_VISITOR';
export const GET_BOOKINGS_STATUS = 'GET_BOOKINGS_STATUS';
export const LOCK_UNIT = 'LOCK_UNIT';
export const CREATE_BOOKING = 'CREATE_BOOKING';
export const GET_BANK_LIST = 'GET_BANK_LIST';

//For  Customer Section
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const GET_BOOKING_DATA = 'GET_BOOKING_DATA';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const GET_BANK_DETAILS = 'GET_BANK_DETAILS';
export const UPDATE_BANK_DETAILS = 'UPDATE_BANK_DETAILS';
export const UPDATE_BANK_FILES = 'UPDATE_BANK_FILES';
export const GET_MODIFY_REQUESTS = 'GET_MODIFY_REQUESTS';
export const ADD_MODIFY_REQUEST = 'ADD_MODIFY_REQUEST';

//For Project Management
export const GET_WORKS = 'GET_WORKS';
export const GET_WORK_CATEGORIES = 'GET_WORK_CATEGORIES';
export const GET_MILESTONES = 'GET_MILESTONES';
export const CREATE_LINEUP_ENTITY = 'CREATE_LINEUP_ENTITY';
export const UPDATE_LINEUP_ENTITY = 'UPDATE_LINEUP_ENTITY';
export const DELETE_LINEUP_ENTITY = 'DELETE_LINEUP_ENTITY';
export const UPDATE_MILESTONE_ORDER = 'UPDATE_MILESTONE_ORDER';
