// For App
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_DRAWER_TYPE = 'SET_DRAWER_TYPE';
export const LOGOUT = 'LOGOUT';
export const SET_TIMER = 'SET_TIMER';

// For Auth/User
export const LOGIN = 'LOGIN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const SIGN_UP_INIT = 'SIGN_UP_INIT';
export const SIGN_UP = 'SIGN_UP';
export const SEND_OTP = 'SEND_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const SELECT_ROLE = 'SELECT_ROLE';
export const UPDATE_USER = 'UPDATE_USER';
export const SEND_FORGET_PASSWORD_OTP = 'SEND_FORGET_PASSWORD_OTP';

// For Notifications
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_PROJECT_NOTIFICATIONS = 'GET_PROJECT_NOTIFICATIONS';
export const REMOVE_ALL_NOTIFICATIONS = 'REMOVE_ALL_NOTIFICATIONS';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// For Project
export const GET_SELECTED_PROJECT = 'GET_SELECTED_PROJECT';
export const SET_CUSTOMER_PROJECT = 'SET_CUSTOMER_PROJECT';
export const GET_PROJECT_PERMISSIONS = 'GET_PROJECT_PERMISSIONS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT_COMMON_DATA = 'GET_PROJECT_COMMON_DATA';
export const SET_SELECTED_UNIT = 'SET_SELECTED_UNIT';
export const GET_PURCHASED_PROJECTS = 'GET_PURCHASED_PROJECTS';
export const GET_PURCHASE_PROJECT_DETAILS = 'GET_PURCHASE_PROJECT_DETAILS';
export const UPDATE_BILLING_DETAILS = 'UPDATE_BILLING_DETAILS';

// For Dashboard
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';

// For Add Project
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_LOCAL_STRUCTURE = 'UPDATE_LOCAL_STRUCTURE';
export const SAVE_STRUCTURE = 'SAVE_STRUCTURE';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const UPDATE_ADMINS = 'UPDATE_ADMINS';
export const RESET_STRUCTURE = 'RESET_STRUCTURE';
export const SET_PROJECT_DATA = 'SET_PROJECT_DATA';
export const GET_STATES = 'GET_STATES';
export const GET_CITIES = 'GET_CITIES';

// For Sales
export const GET_SALES_DATA = 'GET_SALES_DATA';
export const GET_BROKERS_LIST = 'GET_BROKERS_LIST';
export const GET_VISITORS = 'GET_VISITORS';
export const GET_VISITOR = 'GET_VISITOR';
export const ADD_VISITOR = 'ADD_VISITOR';
export const GET_INTERESTED_PROPERTY = 'GET_INTERESTED_PROPERTY';
export const ADD_BROKER = 'ADD_BROKER';
export const ADD_BROKERAGE_PAYMENT = 'ADD_BROKERAGE_PAYMENT';
export const ADD_VISITOR_COMMENT = 'ADD_VISITOR_COMMENT';
export const ADD_VISITOR_CALL_LOGS = 'ADD_VISITOR_CALL_LOGS';
export const ADD_VISITOR_FOLLOW_UP = 'ADD_VISITOR_FOLLOW_UP';
export const ADD_FOLLOW_UP = 'ADD_FOLLOW_UP';
export const UPDATE_FOLLOW_UP = 'UPDATE_FOLLOW_UP';
export const GET_PIPELINES = 'GET_PIPELINES';
export const ADD_PIPELINE = 'ADD_PIPELINE';
export const CONFIRM_BOOKING_OTP = 'CONFIRM_BOOKING_OTP';
export const RESEND_BOOKING_OTP = 'RESEND_BOOKING_OTP';
export const SET_BOOKING_OTP_STATUS = 'SET_BOOKING_OTP_STATUS';
export const GET_BOOKING_FORM_OTP_STATUS = 'GET_BOOKING_FORM_OTP_STATUS';
export const DELETE_PIPELINE = 'DELETE_PIPELINE';
export const DELETE_BROKER = 'DELETE_BROKER';
export const DELETE_BROKERAGE_PAYMENT = 'DELETE_BROKERAGE_PAYMENT';
export const UPDATE_BROKER_REMARK = 'UPDATE_BROKER_REMARK';
export const MOVE_VISITOR = 'MOVE_VISITOR';
export const UPDATE_BROKER = 'UPDATE_BROKER';
export const UPDATE_BROKERAGE_PAYMENT = 'UPDATE_BROKERAGE_PAYMENT';
export const EDIT_BROKERAGE = 'EDIT_BROKERAGE';
export const EDIT_REMARK = 'EDIT_REMARK';
export const GET_BROKER_DETAILS = 'GET_BROKER_DETAILS';
export const GET_BOOKINGS_STATUS = 'GET_BOOKINGS_STATUS';
export const LOCK_UNIT = 'LOCK_UNIT';
export const GET_HOLD_BOOKING_DETAILS = 'GET_HOLD_BOOKING_DETAILS';
export const HOLD_UNIT_BOOKING = 'HOLD_UNIT_BOOKING';
export const UN_HOLD_UNIT_BOOKING = 'UN_HOLD_UNIT_BOOKING';
export const CREATE_BOOKING = 'CREATE_BOOKING';
export const GET_BANK_LIST = 'GET_BANK_LIST';
export const GET_VISITOR_ACTIVITIES = 'GET_VISITOR_ACTIVITIES';
export const GET_PIPELINES_ORDER_LIST = 'GET_PIPELINES_ORDER_LIST';
export const UPDATE_PIPELINE_ORDER_LIST = 'UPDATE_PIPELINE_ORDER_LIST';
export const SET_UPDATED_PIPELINE_DATA = 'SET_UPDATED_PIPELINE_DATA';
export const GET_BROKERAGE_DEAL_DETAILS = 'GET_BROKERAGE_DEAL_DETAILS';

// Approvals
export const GET_APPROVALS = 'GET_APPROVALS';
export const GET_APPROVERS = 'GET_APPROVERS';
export const CREATE_APPROVAL = 'CREATE_APPROVAL';
export const APPROVAL_DETAILS = 'APPROVAL_DETAILS';

// Follow-UP Task

export const GET_FOLLOWUP_LIST = 'GET_FOLLOWUP_LIST';
export const GET_FOLLOWUP_DETAILS_LIST = 'GET_FOLLOWUP_DETAILS_LIST';
export const UPDATE_COMPLETE_TASK = 'UPDATE_COMPLETE_TASK';

// For  Customer Section
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const GET_BOOKING_DATA = 'GET_BOOKING_DATA';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const ADD_MODIFY_REQUEST_COMMENT = 'ADD_MODIFY_REQUEST_COMMENT';
export const GET_BANK_DETAILS = 'GET_BANK_DETAILS';
export const UPDATE_BANK_DETAILS = 'UPDATE_BANK_DETAILS';
export const UPDATE_BANK_FILES = 'UPDATE_BANK_FILES';
export const GET_MODIFY_REQUESTS = 'GET_MODIFY_REQUESTS';
export const ADD_MODIFY_REQUEST = 'ADD_MODIFY_REQUEST';
export const GET_MODIFY_REQUEST = 'GET_MODIFY_REQUEST';
export const UPDATE_MODIFY_REQUEST = 'UPDATE_MODIFY_REQUEST';
export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
export const UPDATE_BOOKING_STATUS = 'UPDATE_BOOKING_STATUS';
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const CUSTOMER_DELETE_FILE = 'CUSTOMER_DELETE_FILE';
export const CUSTOMER_DELETE_FOLDER = 'CUSTOMER_DELETE_FOLDER';

// For Files
export const GET_FOLDERS = 'GET_FOLDERS';
export const CREATE_FOLDER = 'CREATE_FOLDER';
export const RENAME_FOLDER = 'RENAME_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const GET_FILES = 'GET_FILES';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const GET_VERSION = 'GET_VERSION';
export const GET_FILE_ACTIVITIES = 'GET_FILE_ACTIVITIES';
export const RENAME_FILE = 'RENAME_FILE';
export const SHARE_FOLDER_WITH_USERS = 'SHARE_FOLDER_WITH_USERS';
export const SHARE_FILE_WITH_USERS = 'SHARE_FILE_WITH_USERS';
export const ADD_NEW_VERSION = 'ADD_NEW_VERSION';
export const DELETE_VERSION = 'DELETE_VERSION';
export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';
export const GET_CUSTOMER_LIST_DETAILS = 'GET_CUSTOMER_LIST_DETAILS';
export const UPDATE_CUSTOMER_DETAILS = 'UPDATE_CUSTOMER_DETAILS';

// For Design Modules

// Rough Drawing
export const GET_RD_FOLDERS = 'GET_RD_FOLDERS';
export const CREATE_RD_FOLDER = 'CREATE_RD_FOLDER';
export const RENAME_RD_FOLDER = 'RENAME_RD_FOLDER';
export const DELETE_RD_FOLDER = 'DELETE_RD_FOLDER';
export const GET_RD_FOLDER_ACTIVITIES = 'GET_RD_FOLDER_ACTIVITIES';
export const GET_RD_FILES = 'GET_RD_FILES';
export const RENAME_RD_FILES = 'RENAME_RD_FILES';
export const DELETE_RD_FILES = 'DELETE_RD_FILES';
export const DOWNLOAD_RD_FILES = 'DOWNLOAD_RD_FILES';
export const UPLOAD_RD_FILES = 'UPLOAD_RD_FILES';
export const GET_RD_VERSION = 'GET_RD_VERSION';
export const ADD_RD_VERSION = 'ADD_RD_VERSION';
export const DELETE_RD_VERSION = 'DELETE_RD_VERSION';
export const GET_PROJECT_AREA_SHEET = 'GET_PROJECT_AREA_SHEET';
export const UPDATE_AREA_SHEET = 'UPDATE_AREA_SHEET';
export const UPDATE_CATEGORY_TOWER_SHEET = 'UPDATE_CATEGORY_TOWER_SHEET';

// CategorySheet
export const GET_CATEGORY_TOWER_SHEET = 'GET_CATEGORY_TOWER_SHEET';
export const GET_CATEGORY_BUNGALOW_SHEET = 'GET_CATEGORY_BUNGALOW_SHEET';
export const GET_CATEGORY_PLOT_SHEET = 'GET_CATEGORY_PLOT_SHEET';
export const UPDATE_CATEGORY_BUNGALOW_SHEET = 'UPDATE_CATEGORY_BUNGALOW_SHEET';
export const UPDATE_CATEGORY_PLOT_SHEET = 'UPDATE_CATEGORY_PLOT_SHEET';

// Unit Sheet
export const GET_UNIT_TOWER_SHEET = 'GET_UNIT_TOWER_SHEET';
export const UPDATE_UNIT_TOWER_SHEET = 'UPDATE_UNIT_TOWER_SHEET';
export const GET_BUNGALOW_UNIT_SHEET = 'GET_BUNGALOW_UNIT_SHEET';
export const GET_PLOT_UNIT_SHEET = 'GET_PLOT_UNIT_SHEET';
export const UPDATE_BUNGALOW_UNIT_SHEET = 'UPDATE_BUNGALOW_UNIT_SHEET';
export const UPDATE_PLOT_UNIT_SHEET = 'UPDATE_PLOT_UNIT_SHEET';

// Parking
export const GET_PARKING_LIST = 'GET_PARKING_LIST';
export const UPLOAD_PARKING_FILE = 'UPLOAD_PARKING_FILE';
export const DELETE_PARKING_FILE = 'DELETE_PARKING_FILE';
export const UPDATE_PARKING_LIST = 'UPDATE_PARKING_LIST';

// For Project Management
export const GET_WORKS = 'GET_WORKS';
export const GET_WORK_CATEGORIES = 'GET_WORK_CATEGORIES';
export const GET_MILESTONES = 'GET_MILESTONES';
export const CREATE_LINEUP_ENTITY = 'CREATE_LINEUP_ENTITY';
export const UPDATE_LINEUP_ENTITY = 'UPDATE_LINEUP_ENTITY';
export const DELETE_LINEUP_ENTITY = 'DELETE_LINEUP_ENTITY';
export const UPDATE_MILESTONE_ORDER = 'UPDATE_MILESTONE_ORDER';
export const GET_PHASES = 'GET_PHASES';
export const REFRESH_PHASES = 'REFRESH_PHASES';
export const ADD_PHASE = 'ADD_PHASE';
export const UPDATE_PHASE = 'UPDATE_PHASE';
export const DELETE_PHASE = 'DELETE_PHASE';
export const UPDATE_PHASE_ORDER = 'UPDATE_PHASE_ORDER';
export const GET_SUB_PHASES = 'GET_SUB_PHASES';
export const REFRESH_SUB_PHASES = 'REFRESH_SUB_PHASES';
export const ADD_SUB_PHASE = 'ADD_SUB_PHASE';
export const UPDATE_SUB_PHASE = 'UPDATE_SUB_PHASE';
export const DELETE_SUB_PHASE = 'DELETE_SUB_PHASE';
export const GET_PHASE_ACTIVITIES = 'GET_PHASE_ACTIVITIES';
export const ADD_PHASE_ACTIVITY = 'ADD_PHASE_ACTIVITY';
export const UPDATE_PHASE_ACTIVITY = 'UPDATE_PHASE_ACTIVITY';
export const GET_WBS_LEVEL_WORKS = 'GET_WBS_LEVEL_WORKS';
export const WBS_EXECUTION_DETAILS = 'WBS_EXECUTION_DETAILS';
export const WBS_EXECUTION_LIST = 'WBS_EXECUTION_LIST';
export const ADD_PROGRESS_RECORD = 'ADD_PROGRESS_RECORD';

// For Material Managements

export const GET_MATERIAL_ORDER_LIST = 'GET_MATERIAL_ORDER_LIST';
export const GET_SUPPLIERS_LIST = 'GET_SUPPLIERS_LIST';
export const GET_PR_MATERIAL_ORDER_LIST = 'GET_PR_MATERIAL_ORDER_LIST';
export const GET_MATERIAL_LIST = 'GET_MATERIAL_LIST';
export const GET_STORE_KEEPER_LIST = 'GET_STORE_KEEPER_LIST';
export const GET_SELECTED_MATERIAL_CHALLAN = 'GET_SELECTED_MATERIAL_CHALLAN';
export const GET_STORE_KEEPER_DETAILS = 'GET_STORE_KEEPER_DETAILS';
export const GET_MATERIAL_CHALLAN_LIST = 'GET_MATERIAL_CHALLAN_LIST';
export const GET_MATERIAL_CHALLAN_DETAILS = 'GET_MATERIAL_CHALLAN_DETAILS';
export const GET_WORK_SUB_WORK_LIST = 'GET_WORK_SUB_WORK_LIST';
export const GET_VENDOR_OR_CONTRACTORS_DETAILS =
  'GET_VENDOR_OR_CONTRACTORS_DETAILS';
export const GET_MATERIAL_PR_DETAILS = 'GET_MATERIAL_PR_DETAILS';
export const ADD_MATERIAL_CHALLAN = 'ADD_MATERIAL_CHALLAN';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const ADD_DIRECT_GRN = 'ADD_DIRECT_GRN';
export const ADD_DIRECT_GRN_MATERIAL_INFO = 'ADD_DIRECT_GRN_MATERIAL_INFO';
export const ADD_DIRECT_GRN_VEHICLE_INFO = 'ADD_DIRECT_GRN_VEHICLE_INFO';
export const ADD_MATERIAL_PR = 'ADD_MATERIAL_PR';
export const DELETE_CHALLAN = 'DELETE_CHALLAN';
export const CREATE_STOREKEEPER_ORDER = 'CREATE_STOREKEEPER_ORDER';
export const UPDATE_STORE_KEEPER_STATUS = 'UPDATE_STORE_KEEPER_STATUS';
export const GET_SELECT_MATERIAL_CHALLAN = 'GET_SELECT_MATERIAL_CHALLAN';
export const DELETE_ISSUE = 'DELETE_ISSUE';
export const ADD_MATERIAL_ISSUE_REQUEST = 'ADD_MATERIAL_ISSUE_REQUEST';
export const ADD_RETURN_REQUEST = 'ADD_RETURN_REQUEST';
export const CREATE_MATERIAL_PR = 'CREATE_MATERIAL_PR';
export const ADD_ISSUE_REQUEST = 'ADD_ISSUE_REQUEST';
export const EDIT_PR = 'EDIT_PR';
export const GET_MATERIAL_INDENT_DETAILS = 'GET_MATERIAL_INDENT_DETAILS';
export const ADD_ATTACHMENT = 'ADD_ATTACHMENT';
export const EDIT_MATERIAL_PR = 'EDIT_MATERIAL_PR';
export const DELETE_MATERIAL_PR_DETAILS = 'DELETE_MATERIAL_PR_DETAILS';
export const DELETE_MATERIAL_PR_ITEM = 'DELETE_MATERIAL_PR_ITEM';
export const DELETE_MATERIAL_PR_CATEGORY = 'DELETE_MATERIAL_PR_CATEGORY';
export const DELETE_MATERIAL_DIRECT_GRN = 'DELETE_MATERIAL_DIRECT_GRN';
export const UPDATE_PR_STATUS = 'UPDATE_PR_STATUS';
export const UPDATE_DIRECT_GRN_STATUS = 'UPDATE_DIRECT_GRN_STATUS';
export const GET_DIRECT_GRN_LIST = 'GET_DIRECT_GRN_LIST';
export const GET_DIRECT_GRN_DETAILS = 'GET_DIRECT_GRN_DETAILS';
export const GET_MATERIAL_GRN_DETAILS = 'GET_MATERIAL_GRN_DETAILS';
export const GET_MATERIAL_INDENT_LIST = 'GET_MATERIAL_INDENT_LIST';

// For Role and Members
export const GET_MEMBERS = 'GET_MEMBERS';
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLE_DETAILS = 'GET_ROLE_DETAILS';
export const ADD_USERS = 'ADD_USERS';
export const ADD_ROLE = 'ADD_ROLE';
export const EDIT_USERS = 'EDIT_USERS';
export const DELETE_ROLE = 'DELETE_ROLE';
export const DELETE_MEMBER = 'DELETE_MEMBER';
