export const PIList = [
  {
    id: 1,
    inquiryDate: '23 Jul, 2022 ',
    validityDate: '01 Aug',
    status: 'Pending',
    createdBy: 'Chirag Pithadiya',
    shared: '05',
    submitted: '25',
  },
  {
    id: 2,
    inquiryDate: '23 Jul, 2022 ',
    validityDate: '01 Aug',
    createdBy: 'Chirag Pithadiya',
    shared: '05',
    submitted: '25',
    status: 'Approved',
  },
  {
    id: 3,
    inquiryDate: '23 Jul, 2022 ',
    validityDate: '01 Aug',
    status: 'Rejected',
    createdBy: 'Chirag Pithadiya',
    shared: '05',
    submitted: '25',
  },
  {
    id: 4,
    inquiryDate: '23 Jul, 2022 ',
    validityDate: '01 Aug',
    createdBy: 'Chirag Pithadiya',
    shared: '05',
    submitted: '25',
    status: 'Pending',
  },
  {
    id: 5,
    inquiryDate: '23 Jul, 2022 ',
    validityDate: '01 Aug',
    createdBy: 'Chirag Pithadiya',
    shared: '05',
    submitted: '25',
    status: 'Pending',
  },
  {
    id: 6,
    inquiryDate: '23 Jul, 2022 ',
    validityDate: '01 Aug',
    createdBy: 'Chirag Pithadiya',
    shared: '05',
    submitted: '25',
    status: 'Pending',
  },
];
