export const PIData = [
  {
    id: 1,
    status: 'Pending',
    inquiryDT: '23 Jul, 2022',
    validityDT: '01 Aug, 2022',
    createdBy: 'Himanshu Nanikwal',
    shared: 5,
    submitted: 25,
  },
  {
    id: 2,
    status: 'Approved',
    inquiryDT: '23 Jul, 2022',
    validityDT: '01 Aug, 2022',
    createdBy: 'Himanshu Nanikwal',
    shared: 5,
    submitted: 25,
  },
  {
    id: 3,
    status: 'Rejected',
    inquiryDT: '23 Jul, 2022',
    validityDT: '01 Aug, 2022',
    createdBy: 'Himanshu Nanikwal',
    shared: 5,
    submitted: 25,
  },
  {
    id: 4,
    status: 'Pending',
    inquiryDT: '23 Jul, 2022',
    validityDT: '01 Aug, 2022',
    createdBy: 'Himanshu Nanikwal',
    shared: 5,
    submitted: 25,
  },
  {
    id: 5,
    status: 'Rejected',
    inquiryDT: '23 Jul, 2022',
    validityDT: '01 Aug, 2022',
    createdBy: 'Himanshu Nanikwal',
    shared: 5,
    submitted: 25,
  },
  {
    id: 6,
    status: 'Pending',
    inquiryDT: '23 Jul, 2022',
    validityDT: '01 Aug, 2022',
    createdBy: 'Himanshu Nanikwal',
    shared: 5,
    submitted: 25,
  },
];
