export const ProjectData = [
  {
    id: 1,
    project_name: 'Park Ave Penthouse',
    developer_name: 'Jayesh Bhai',
    area: 'devnagar gota',
    pincode: '382481',
    city: 'ahmedabad',
    state: 'gujarat',
    country: 'india',
    status: 1,
    premium_project: 1,
  },
  {
    id: 2,
    project_name: 'Avishkar Atlantis',
    developer_name: 'Ramesh Kalrav',
    area: 'Science city',
    pincode: '380060',
    city: 'ahmedabad',
    state: 'gujarat',
    country: 'india',
    status: 0,
    premium_project: 0,
  },
  {
    id: 3,
    project_name: 'Satyamev',
    developer_name: 'Mahesh Saini',
    area: 'Sola Road',
    pincode: '381234',
    city: 'ahmedabad',
    state: 'gujarat',
    country: 'india',
    status: 0,
    premium_project: 1,
  },
  {
    id: 4,
    project_name: 'Tri',
    developer_name: 'Parth Patel',
    area: 'Bodakdev',
    pincode: '397614',
    city: 'ahmedabad',
    state: 'gujarat',
    country: 'india',
    status: 1,
    premium_project: 0,
  },
  {
    id: 5,
    project_name: 'Capestone',
    developer_name: 'Suresh Sharma',
    area: 'Gandhinagar',
    pincode: '895412',
    city: 'ahmedabad',
    state: 'gujarat',
    country: 'india',
    status: 0,
    premium_project: 1,
  },
];
