export const MaterialIndentData = [
  {
    id: 1,
    validityDate: '01 Aug',
    status: 'Pending',
    createdBy: 'Ronak Veghani',
    createrEmail: 'ronak@builformula.com',
    query: 'Ask for Material',
  },
  {
    id: 2,
    validityDate: '01 Aug',
    createdBy: 'Dixit Parmar',
    status: 'Rejected',
    createrEmail: 'dixitparmar@builformula.com',
    query: 'Ask for Material',
  },
  {
    id: 3,
    validityDate: '01 Aug',
    status: 'Approved',
    createdBy: 'Uttam Kotiya',
    createrEmail: 'uttamkotiya12@buildformula.com',
    query: 'Ask for Material',
  },
  {
    id: 4,
    validityDate: '01 Aug',
    status: 'Pending',
    createdBy: 'Uttam Kotiya',
    createrEmail: 'uttamkotiya12@buildformula.com',
    query: 'Return Material',
  },
  {
    id: 5,
    validityDate: '01 Aug',
    status: 'Approved',
    createdBy: 'Ronak Veghani',
    createrEmail: 'ronak@builformula.com',
    query: 'Ask for Material',
  },
  {
    id: 6,
    validityDate: '01 Aug',
    status: 'Pending',
    createdBy: 'Uttam Kotiya',
    createrEmail: 'uttamkotiya12@buildformula.com',
    query: 'Return Material',
  },
];
