export const STORE_KEEPER_DATA = [
  {
    id: 1,
    validityDate: '3rd Sep, 2022',
    status: 'Pending',
    createdBy: 'Ronak Veghani',
    createrEmail: 'ronak@builformula.com',
    query: 'Ask for Material',
    authorizedName: 'Hiren Surani',
    authorizedEmail: ' Hirens12@buildformula.com',
    authorizedDate: '3rd Sep, 2022',
  },
  {
    id: 2,
    validityDate: '3rd Sep, 2022',
    createdBy: 'Dixit Parmar',
    status: 'Rejected',
    createrEmail: 'dixitparmar@builformula.com',
    query: 'Return Material',
  },
  {
    id: 3,
    validityDate: '3rd Sep, 2022',
    status: 'Approved',
    createdBy: 'Uttam Kotiya',
    createrEmail: 'uttamkotiya12@buildformula.com',
    query: 'Ask for Material',
    authorizedName: 'Hiren Surani',
    authorizedEmail: ' Hirens12@buildformula.com',
    authorizedDate: '3rd Sep, 2022',
  },
  {
    id: 4,
    validityDate: '3rd Sep, 2022',
    status: 'Pending',
    createdBy: 'Uttam Kotiya',
    createrEmail: 'uttamkotiya12@buildformula.com',
    query: 'Return Material',
    authorizedName: 'Hiren Surani',
    authorizedEmail: ' Hirens12@buildformula.com',
    authorizedDate: '3rd Sep, 2022',
  },
  {
    id: 5,
    validityDate: '3rd Sep, 2022',
    status: 'Approved',
    createdBy: 'Ronak Veghani',
    createrEmail: 'ronak@builformula.com',
    query: 'Ask for Material',
    authorizedName: 'Hiren Surani',
    authorizedEmail: ' Hirens12@buildformula.com',
    authorizedDate: '3rd Sep, 2022',
  },
  {
    id: 6,
    validityDate: '3rd Sep, 2022',
    status: 'Pending',
    createdBy: 'Uttam Kotiya',
    createrEmail: 'uttamkotiya12@buildformula.com',
    query: 'Return Material',
  },
];
